/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as StructureRouteImport } from './routes/structure'
import { Route as PagesIndexRouteImport } from './routes/pages/index'
import { Route as PagesAnalyticsRouteImport } from './routes/pages/analytics'
import { Route as PagesBillingRouteImport } from './routes/pages/billing'
import { Route as PagesDashboardRouteImport } from './routes/pages/dashboard'
import { Route as PagesDocsRouteImport } from './routes/pages/docs'
import { Route as PagesInboxRouteImport } from './routes/pages/inbox'
import { Route as PagesProfileRouteImport } from './routes/pages/profile'
import { Route as PagesSettingsRouteImport } from './routes/pages/settings'
import { Route as PagesTeamRouteImport } from './routes/pages/team'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const StructureRoute = StructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesIndexRoute = PagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesRoute,
} as any)
const PagesAnalyticsRoute = PagesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PagesRoute,
} as any)
const PagesBillingRoute = PagesBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDashboardRoute = PagesDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PagesRoute,
} as any)
const PagesDocsRoute = PagesDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PagesRoute,
} as any)
const PagesInboxRoute = PagesInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => PagesRoute,
} as any)
const PagesProfileRoute = PagesProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PagesRoute,
} as any)
const PagesSettingsRoute = PagesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PagesRoute,
} as any)
const PagesTeamRoute = PagesTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/pages': typeof PagesRouteWithChildren
  '/structure': typeof StructureRoute
  '/pages/analytics': typeof PagesAnalyticsRoute
  '/pages/billing': typeof PagesBillingRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/docs': typeof PagesDocsRoute
  '/pages/inbox': typeof PagesInboxRoute
  '/pages/profile': typeof PagesProfileRoute
  '/pages/settings': typeof PagesSettingsRoute
  '/pages/team': typeof PagesTeamRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/structure': typeof StructureRoute
  '/pages/analytics': typeof PagesAnalyticsRoute
  '/pages/billing': typeof PagesBillingRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/docs': typeof PagesDocsRoute
  '/pages/inbox': typeof PagesInboxRoute
  '/pages/profile': typeof PagesProfileRoute
  '/pages/settings': typeof PagesSettingsRoute
  '/pages/team': typeof PagesTeamRoute
  '/pages': typeof PagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/pages': typeof PagesRouteWithChildren
  '/structure': typeof StructureRoute
  '/pages/analytics': typeof PagesAnalyticsRoute
  '/pages/billing': typeof PagesBillingRoute
  '/pages/dashboard': typeof PagesDashboardRoute
  '/pages/docs': typeof PagesDocsRoute
  '/pages/inbox': typeof PagesInboxRoute
  '/pages/profile': typeof PagesProfileRoute
  '/pages/settings': typeof PagesSettingsRoute
  '/pages/team': typeof PagesTeamRoute
  '/pages/': typeof PagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/pages'
    | '/structure'
    | '/pages/analytics'
    | '/pages/billing'
    | '/pages/dashboard'
    | '/pages/docs'
    | '/pages/inbox'
    | '/pages/profile'
    | '/pages/settings'
    | '/pages/team'
    | '/pages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/structure'
    | '/pages/analytics'
    | '/pages/billing'
    | '/pages/dashboard'
    | '/pages/docs'
    | '/pages/inbox'
    | '/pages/profile'
    | '/pages/settings'
    | '/pages/team'
    | '/pages'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/pages'
    | '/structure'
    | '/pages/analytics'
    | '/pages/billing'
    | '/pages/dashboard'
    | '/pages/docs'
    | '/pages/inbox'
    | '/pages/profile'
    | '/pages/settings'
    | '/pages/team'
    | '/pages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  PagesRoute: typeof PagesRouteWithChildren
  StructureRoute: typeof StructureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/structure': {
      id: '/structure'
      path: '/structure'
      fullPath: '/structure'
      preLoaderRoute: typeof StructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/': {
      id: '/pages/'
      path: '/'
      fullPath: '/pages/'
      preLoaderRoute: typeof PagesIndexRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/analytics': {
      id: '/pages/analytics'
      path: '/analytics'
      fullPath: '/pages/analytics'
      preLoaderRoute: typeof PagesAnalyticsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/billing': {
      id: '/pages/billing'
      path: '/billing'
      fullPath: '/pages/billing'
      preLoaderRoute: typeof PagesBillingRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/dashboard': {
      id: '/pages/dashboard'
      path: '/dashboard'
      fullPath: '/pages/dashboard'
      preLoaderRoute: typeof PagesDashboardRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/docs': {
      id: '/pages/docs'
      path: '/docs'
      fullPath: '/pages/docs'
      preLoaderRoute: typeof PagesDocsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/inbox': {
      id: '/pages/inbox'
      path: '/inbox'
      fullPath: '/pages/inbox'
      preLoaderRoute: typeof PagesInboxRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/profile': {
      id: '/pages/profile'
      path: '/profile'
      fullPath: '/pages/profile'
      preLoaderRoute: typeof PagesProfileRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/settings': {
      id: '/pages/settings'
      path: '/settings'
      fullPath: '/pages/settings'
      preLoaderRoute: typeof PagesSettingsRouteImport
      parentRoute: typeof PagesRoute
    }
    '/pages/team': {
      id: '/pages/team'
      path: '/team'
      fullPath: '/pages/team'
      preLoaderRoute: typeof PagesTeamRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface PagesRouteChildren {
  PagesAnalyticsRoute: typeof PagesAnalyticsRoute
  PagesBillingRoute: typeof PagesBillingRoute
  PagesDashboardRoute: typeof PagesDashboardRoute
  PagesDocsRoute: typeof PagesDocsRoute
  PagesInboxRoute: typeof PagesInboxRoute
  PagesProfileRoute: typeof PagesProfileRoute
  PagesSettingsRoute: typeof PagesSettingsRoute
  PagesTeamRoute: typeof PagesTeamRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesAnalyticsRoute: PagesAnalyticsRoute,
  PagesBillingRoute: PagesBillingRoute,
  PagesDashboardRoute: PagesDashboardRoute,
  PagesDocsRoute: PagesDocsRoute,
  PagesInboxRoute: PagesInboxRoute,
  PagesProfileRoute: PagesProfileRoute,
  PagesSettingsRoute: PagesSettingsRoute,
  PagesTeamRoute: PagesTeamRoute,
  PagesIndexRoute: PagesIndexRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  PagesRoute: PagesRouteWithChildren,
  StructureRoute: StructureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
